USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_SITE_LATEST]') AND type in (N'U'))
DROP TABLE [dbo].DIM_SITE_LATEST
GO

SELECT * 
INTO DIM_SITE_LATEST
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT TENANT_DK
	  ,SITE_DK
	  ,CUSTOMER_DK
	  ,CAST(SUBSTRING(SYSTEM_GUID,1,8000) AS CHAR(8000)) AS SYSTEM_GUID
	  ,CAST(SUBSTRING(BIZ_APPS_CUST_ID,1,8000) AS CHAR(8000)) AS BIZ_APPS_CUST_ID
	  ,CUSTOMER_ID
	  ,PARENT_ID
	  ,CAST(SUBSTRING(NAME,1,8000) AS CHAR(8000)) AS NAME
	  ,CREATED
	  ,VALID_FROM
	  ,VALID_TO
	  ,CURRENT_FLAG
	  ,DSS_IS_DELETE
	  ,DSS_CREATED
	  ,DSS_UPDATED
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_SITE_LATEST')
