USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_PATCH_ACTION_STATUS_TYPE]') AND type in (N'U'))
DROP TABLE [dbo].[DIM_PATCH_ACTION_STATUS_TYPE]
GO

SELECT * 
INTO DIM_PATCH_ACTION_STATUS_TYPE
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT PATCH_ACTION_STATUS_TYPE_DK
	  ,CAST(SUBSTRING(PATCH_ACTION_STATUS,1,8000) AS CHAR(8000)) AS PATCH_ACTION_STATUS
	  ,CAST(SUBSTRING(PATCH_ACTION_TYPE,1,8000) AS CHAR(8000)) AS PATCH_ACTION_TYPE
	  ,DSS_CREATED
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_PATCH_ACTION_STATUS_TYPE')
