USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_ANTIVIRUS_OUTCOME]') AND type in (N'U'))
DROP TABLE [dbo].[DIM_ANTIVIRUS_OUTCOME]
GO

SELECT * 
INTO DIM_ANTIVIRUS_OUTCOME
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT ANTIVIRUS_OUTCOME_DK
	  ,CAST(SUBSTRING(OUTCOME_TYPE,1,8000) AS CHAR(8000)) AS OUTCOME_TYPE
	  ,STATE_ID
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_ANTIVIRUS_OUTCOME')
