USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_BACKUP_STATUS]') AND type in (N'U'))
DROP TABLE [dbo].[DIM_BACKUP_STATUS]
GO

SELECT * 
INTO DIM_BACKUP_STATUS
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT BACKUP_STATUS_DK
	  ,BACKUP_STATUS_ID
	  ,CAST(SUBSTRING(BACKUP_STATUS_DESCRIPTION,1,8000) AS CHAR(8000)) AS BACKUP_STATUS_DESCRIPTION
	  ,CAST(SUBSTRING(BACKUP_STATUS_NAME,1,8000) AS CHAR(8000)) AS BACKUP_STATUS_NAME
	  ,BACKUP_STATUS_SK
	  ,CAST(SUBSTRING(ERROR_STATUS,1,8000) AS CHAR(8000)) AS ERROR_STATUS
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_BACKUP_STATUS')
