USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_DATE]') AND type in (N'U'))
DROP TABLE [dbo].[DIM_DATE]
GO

SELECT * 
INTO DIM_DATE
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT DATE_SK
	  ,DATE_DK
	  ,CALENDAR_DATE
	  ,CAST(SUBSTRING(CAL_DAY_IN_WEEK,1,8000) AS CHAR(8000)) AS CAL_DAY_IN_WEEK
	  ,CAL_DAY_IN_WEEK_NO
	  ,CAL_DAY_IN_MONTH
	  ,CAL_DAY_IN_YEAR
	  ,CAL_MONTH_NO
	  ,CAL_MONTH
	  ,CAST(SUBSTRING(CAL_MONTH_NAME,1,8000) AS CHAR(8000)) AS CAL_MONTH_NAME
	  ,CAL_QUARTER_NO
	  ,CAL_QUARTER
	  ,CAL_YEAR
	  ,CAST(SUBSTRING(WEEK_DAY_FLAG,1,8000) AS CHAR(8000)) AS WEEK_DAY_FLAG
	  ,CAST(SUBSTRING(WEEK_END_FLAG,1,8000) AS CHAR(8000)) AS WEEK_END_FLAG
	  ,CAL_WEEK_IN_YEAR
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_DATE')
