USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_SERVICE]') AND type in (N'U'))
DROP TABLE [dbo].DIM_SERVICE
GO

SELECT * 
INTO DIM_SERVICE
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT TENANT_DK
	  ,SERVICE_INSTANCE_DK
	  ,SERVICE_INSTANCE_ID
	  ,CAST(SUBSTRING(SERVICE_DOMAIN,1,8000) AS CHAR(8000)) AS SERVICE_DOMAIN
	  ,CAST(SUBSTRING(SERVICE_CATEGORY,1,8000) AS CHAR(8000)) AS SERVICE_CATEGORY
	  ,STOCK_SERVICE_FLAG
	  ,CAST(SUBSTRING(SERVICE_INSTANCE_NAME,1,8000) AS CHAR(8000)) AS SERVICE_INSTANCE_NAME
	  ,CAST(SUBSTRING(SERVICE_INSTANCE_DESCRIPTION,1,8000) AS CHAR(8000)) AS SERVICE_INSTANCE_DESCRIPTION
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_SERVICE')
