USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_DOMAIN_USER]') AND type in (N'U'))
DROP TABLE [dbo].[DIM_DOMAIN_USER]
GO

SELECT * 
INTO DIM_DOMAIN_USER
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT TENANT_DK
	  ,DOMAIN_USER_DK
	  ,CAST(SUBSTRING(DOMAIN,1,8000) AS CHAR(8000)) AS DOMAIN
	  ,CAST(SUBSTRING(USER_NAME,1,8000) AS CHAR(8000)) AS USER_NAME
	  ,DSS_CREATED
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_DOMAIN_USER')
