USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_END_DATE]') AND type in (N'U'))
DROP TABLE [dbo].[DIM_END_DATE]
GO

SELECT * 
INTO DIM_END_DATE
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT END_DATE_SK
	  ,END_DATE_DK
	  ,END_CALENDAR_DATE
	  ,CAST(SUBSTRING(END_CAL_DAY_IN_WEEK,1,8000) AS CHAR(8000)) AS END_CAL_DAY_IN_WEEK
	  ,END_CAL_DAY_IN_WEEK_NO
	  ,END_CAL_DAY_IN_MONTH
	  ,END_CAL_DAY_IN_YEAR
	  ,END_CAL_MONTH_NO
	  ,END_CAL_MONTH
	  ,CAST(SUBSTRING(END_CAL_MONTH_NAME,1,8000) AS CHAR(8000)) AS END_CAL_MONTH_NAME
	  ,END_CAL_QUARTER_NO
	  ,END_CAL_QUARTER
	  ,END_CAL_YEAR
	  ,CAST(SUBSTRING(END_WEEK_DAY_FLAG,1,8000) AS CHAR(8000)) AS END_WEEK_DAY_FLAG
	  ,CAST(SUBSTRING(END_WEEK_END_FLAG,1,8000) AS CHAR(8000)) AS END_WEEK_END_FLAG
	  ,END_CAL_WEEK_IN_YEAR
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_END_DATE')
