USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_ANTIVIRUS_THREAT]') AND type in (N'U'))
DROP TABLE [dbo].[DIM_ANTIVIRUS_THREAT]
GO

SELECT * 
INTO DIM_ANTIVIRUS_THREAT
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT ANTIVIRUS_THREAT_DK
	  ,CAST(SUBSTRING(MALWARE_TYPE,1,8000) AS CHAR(8000)) AS MALWARE_TYPE
	  ,MALWARE_TYPE_ID
	  ,CAST(SUBSTRING(MALWARE_TYPE,1,8000) AS CHAR(8000)) AS THREAT_TYPE
	  ,THREAT_TYPE_ID
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_ANTIVIRUS_THREAT')
