USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_ANTIVIRUS_ACTION]') AND type in (N'U'))
DROP TABLE [dbo].[DIM_ANTIVIRUS_ACTION]
GO

SELECT * 
INTO DIM_ANTIVIRUS_ACTION
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT ANTIVIRUS_ACTION_DK
	  ,CAST(SUBSTRING(ANTIVIRUS_ACTION_DESCRIPTION,1,8000) AS CHAR(8000)) AS ANTIVIRUS_ACTION_DESCRIPTION
	  ,IS_DISINFECT
	  ,IS_DENY_IGNORE
	  ,IS_MOVE_QUARANTINE
	  ,IS_DELETE
	  ,IS_DISINFECT_ONLY
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_ANTIVIRUS_ACTION')
