USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_PHYSICAL_STORAGE]') AND type in (N'U'))
DROP TABLE [dbo].[DIM_PHYSICAL_STORAGE]
GO

SELECT * 
INTO DIM_PHYSICAL_STORAGE
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT TENANT_DK
	  ,STORAGE_DK
	  ,CAST(SUBSTRING(MEDIA_TYPE,1,8000) AS CHAR(8000)) AS MEDIA_TYPE
	  ,CAST(SUBSTRING(MEDIA_TYPE_DERIVED,1,8000) AS CHAR(8000)) AS MEDIA_TYPE_DERIVED
	  ,CAST(SUBSTRING(DESCRIPTION,1,8000) AS CHAR(8000)) AS DESCRIPTION
	  ,DSS_CREATED
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_PHYSICAL_STORAGE')
