USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_REMOTE_EXECUTION_TYPE]') AND type in (N'U'))
DROP TABLE [dbo].DIM_REMOTE_EXECUTION_TYPE
GO

SELECT * 
INTO DIM_REMOTE_EXECUTION_TYPE
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT TENANT_DK
	  ,REMOTE_EXECUTION_TYPE_DK
	  ,CAST(SUBSTRING(TASK_TYPE,1,8000) AS CHAR(8000)) AS TASK_TYPE
	  ,CAST(SUBSTRING(TASK_TYPE_NAME,1,8000) AS CHAR(8000)) AS TASK_TYPE_NAME
	  ,CAST(SUBSTRING(TASK_NAME,1,8000) AS CHAR(8000)) AS TASK_NAME
	  ,DSS_CREATED
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_REMOTE_EXECUTION_TYPE')
