USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[STAGING_DIM_PATCH_ANDR]') AND type in (N'U'))
	DROP TABLE [dbo].[STAGING_DIM_PATCH_ANDR]
GO

SELECT * 
INTO STAGING_DIM_PATCH_ANDR
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT PATCH_SK
	  ,TENANT_DK
	  ,PATCH_DK
	  ,CAST(SUBSTRING(PATCH_GUID,1,8000) AS CHAR(8000)) AS PATCH_GUID
	  ,CAST(SUBSTRING(NAME,1,8000) AS CHAR(8000)) AS NAME
	  ,CAST(SUBSTRING(DESCRIPTION,1,8000) AS CHAR(8000)) AS DESCRIPTION
	  ,CAST(SUBSTRING(SEVERITY,1,8000) AS CHAR(8000)) AS SEVERITY
	  ,CAST(SUBSTRING(INFO_URLS,1,8000) AS CHAR(8000)) AS INFO_URLS
	  ,CAST(SUBSTRING(KB_NUMBER,1,8000) AS CHAR(8000)) AS KB_NUMBER
	  ,CAST(SUBSTRING(LANGUAGES_SUPPORTED,1,8000) AS CHAR(8000)) AS LANGUAGES_SUPPORTED
	  ,CAST(SUBSTRING(PATCH_CATEGORY_NAME,1,8000) AS CHAR(8000)) AS PATCH_CATEGORY_NAME
	  ,CAST(PUBLISH_DATE AS VARCHAR(8000)) AS PUBLISH_DATE
	  ,CAST(SUBSTRING(PATCH_SOURCE,1,8000) AS CHAR(8000)) AS PATCH_SOURCE
	  ,CAST(SUBSTRING(PATCH_VENDOR,1,8000) AS CHAR(8000)) AS PATCH_VENDOR
	  ,CAST(SUBSTRING(SUPERSEDING,1,8000) AS CHAR(8000)) AS SUPERSEDING
	  ,CAST(SUBSTRING(SUPERSEDED_BY,1,8000) AS CHAR(8000)) AS SUPERSEDED_BY
	  ,IS_SUPERSEDED
	  ,DSS_IS_DELETE
	  ,CAST(DSS_CREATED AS VARCHAR(8000)) AS DSS_CREATED
	  ,CAST(DSS_UPDATED AS VARCHAR(8000)) AS DSS_UPDATED
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_PATCH_ANDR
    WHERE (DSS_CREATED >= DATEADD(DAY, -3, CURRENT_TIMESTAMP()) AND DSS_CREATED <= DATEADD(DAY, 0, CURRENT_TIMESTAMP()))
       OR (DSS_UPDATED >= DATEADD(DAY, -3, CURRENT_TIMESTAMP()) AND DSS_UPDATED <= DATEADD(DAY, 0, CURRENT_TIMESTAMP()))')

	  
-- Merge statement
MERGE [dbo].[DIM_PATCH_ANDR] AS TARGET
USING [dbo].[STAGING_DIM_PATCH_ANDR] AS SOURCE
     ON TARGET.TENANT_DK	= SOURCE.TENANT_DK
	AND TARGET.PATCH_SK		= SOURCE.PATCH_SK
	AND TARGET.PATCH_DK		= SOURCE.PATCH_DK
	AND TARGET.PATCH_GUID	= SOURCE.PATCH_GUID

WHEN MATCHED AND (
    TARGET.NAME <> SOURCE.NAME OR
    TARGET.DESCRIPTION <> SOURCE.DESCRIPTION OR
    TARGET.SEVERITY <> SOURCE.SEVERITY OR
    TARGET.INFO_URLS <> SOURCE.INFO_URLS OR
    TARGET.KB_NUMBER <> SOURCE.KB_NUMBER OR
    TARGET.LANGUAGES_SUPPORTED <> SOURCE.LANGUAGES_SUPPORTED OR
    TARGET.PATCH_CATEGORY_NAME <> SOURCE.PATCH_CATEGORY_NAME OR
    TRY_CONVERT(datetime2(3), TARGET.PUBLISH_DATE) <> TRY_CONVERT(datetime2(3), SOURCE.PUBLISH_DATE) OR
    TARGET.PATCH_SOURCE <> SOURCE.PATCH_SOURCE OR
    TARGET.PATCH_VENDOR <> SOURCE.PATCH_VENDOR OR
    TARGET.SUPERSEDING <> SOURCE.SUPERSEDING OR
    TARGET.SUPERSEDED_BY <> SOURCE.SUPERSEDED_BY OR
    TARGET.IS_SUPERSEDED <> SOURCE.IS_SUPERSEDED OR
    TARGET.DSS_IS_DELETE <> SOURCE.DSS_IS_DELETE OR
    TARGET.DSS_CREATED <> SOURCE.DSS_CREATED OR
    TARGET.DSS_UPDATED <> SOURCE.DSS_UPDATED
)

THEN UPDATE SET
    TARGET.NAME = SOURCE.NAME,
    TARGET.DESCRIPTION = SOURCE.DESCRIPTION,
    TARGET.SEVERITY = SOURCE.SEVERITY,
    TARGET.INFO_URLS = SOURCE.INFO_URLS,
    TARGET.KB_NUMBER = SOURCE.KB_NUMBER,
    TARGET.LANGUAGES_SUPPORTED = SOURCE.LANGUAGES_SUPPORTED,
    TARGET.PATCH_CATEGORY_NAME = SOURCE.PATCH_CATEGORY_NAME,
    TARGET.PUBLISH_DATE = SOURCE.PUBLISH_DATE,
    TARGET.PATCH_SOURCE = SOURCE.PATCH_SOURCE,
    TARGET.PATCH_VENDOR = SOURCE.PATCH_VENDOR,
    TARGET.SUPERSEDING = SOURCE.SUPERSEDING,
    TARGET.SUPERSEDED_BY = SOURCE.SUPERSEDED_BY,
    TARGET.IS_SUPERSEDED = SOURCE.IS_SUPERSEDED,
    TARGET.DSS_IS_DELETE = SOURCE.DSS_IS_DELETE,
    TARGET.DSS_CREATED = SOURCE.DSS_CREATED,
    TARGET.DSS_UPDATED = SOURCE.DSS_UPDATED

WHEN NOT MATCHED BY TARGET THEN
INSERT (
    TENANT_DK, PATCH_SK, PATCH_DK, PATCH_GUID, 
	NAME, DESCRIPTION, SEVERITY, INFO_URLS, KB_NUMBER, LANGUAGES_SUPPORTED, PATCH_CATEGORY_NAME, PUBLISH_DATE, 
	PATCH_SOURCE, PATCH_VENDOR, SUPERSEDING, SUPERSEDED_BY, IS_SUPERSEDED, DSS_IS_DELETE,
    DSS_CREATED, DSS_UPDATED
)
VALUES (
    SOURCE.TENANT_DK, SOURCE.PATCH_SK, SOURCE.PATCH_DK, SOURCE.PATCH_GUID,
    SOURCE.NAME, SOURCE.DESCRIPTION, SOURCE.SEVERITY,
    SOURCE.INFO_URLS, SOURCE.KB_NUMBER, SOURCE.LANGUAGES_SUPPORTED, SOURCE.PATCH_CATEGORY_NAME,
    SOURCE.PUBLISH_DATE, SOURCE.PATCH_SOURCE, SOURCE.PATCH_VENDOR,
    SOURCE.SUPERSEDING, SOURCE.SUPERSEDED_BY, SOURCE.IS_SUPERSEDED, SOURCE.DSS_IS_DELETE,
    SOURCE.DSS_CREATED, SOURCE.DSS_UPDATED
);
