USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_UTILIZATION_PROFILE]') AND type in (N'U'))
DROP TABLE [dbo].DIM_UTILIZATION_PROFILE
GO

SELECT * 
INTO DIM_UTILIZATION_PROFILE
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT UTILIZATION_PROFILE_DK
	  ,CAST(SUBSTRING(UTILIZATION_TYPE,1,8000) AS CHAR(8000)) AS UTILIZATION_TYPE
	  ,CAST(SUBSTRING(UNIT_TYPE,1,8000) AS CHAR(8000)) AS UNIT_TYPE
	  ,CAST(SUBSTRING(NAME,1,8000) AS CHAR(8000)) AS NAME
	  ,CAST(SUBSTRING(PROFILE_NAME,1,8000) AS CHAR(8000)) AS PROFILE_NAME
	  ,DSS_CREATED
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_UTILIZATION_PROFILE')
