USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_REMOTE_ACCESS_CONNECTION]') AND type in (N'U'))
DROP TABLE [dbo].[DIM_REMOTE_ACCESS_CONNECTION]
GO

SELECT * 
INTO DIM_REMOTE_ACCESS_CONNECTION
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT CONNECTION_DK
	  ,CAST(SUBSTRING(CONNECTION_TYPE_KNOWN_AS,1,8000) AS CHAR(8000)) AS CONNECTION_TYPE_KNOWN_AS
	  ,CAST(SUBSTRING(METHOD,1,8000) AS CHAR(8000)) AS METHOD
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_REMOTE_ACCESS_CONNECTION')
