USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_VIDEO_CONTROLLER]') AND type in (N'U'))
DROP TABLE [dbo].DIM_VIDEO_CONTROLLER
GO

SELECT * 
INTO DIM_VIDEO_CONTROLLER
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT VIDEO_CONTROLLER_NAME_DK
	  ,CAST(SUBSTRING(NAME,1,8000) AS CHAR(8000)) AS NAME
	  ,CAST(SUBSTRING(MANUFACTURER,1,8000) AS CHAR(8000)) AS MANUFACTURER
	  ,CAST(SUBSTRING(DESCRIPTION,1,8000) AS CHAR(8000)) AS DESCRIPTION
	  ,DSS_CREATED
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_VIDEO_CONTROLLER')
