USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_CUSTOMER]') AND type in (N'U'))
DROP TABLE [dbo].[DIM_CUSTOMER]
GO

SELECT * 
INTO DIM_CUSTOMER
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT CUSTOMER_DK
	  ,CUSTOMER_SK
	  ,TENANT_DK
	  ,VAR_DK
	  ,CAST(SUBSTRING(SYSTEM_GUID,1,8000) AS CHAR(8000)) AS SYSTEM_GUID
	  ,CAST(SUBSTRING(BIZ_APPS_CUST_ID,1,8000) AS CHAR(8000)) AS BIZ_APPS_CUST_ID
	  ,CUSTOMER_ID
	  ,PARENT_ID
	  ,CAST(SUBSTRING(NAME,1,8000) AS CHAR(8000)) AS NAME
	  ,CREATED
	  ,VALID_FROM
	  ,CURRENT_FLAG
	  ,DSS_IS_DELETE
	  ,DSS_CREATED
	  ,DSS_UPDATED
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_CUSTOMER')
