USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_ANTIVIRUS_PRODUCT]') AND type in (N'U'))
DROP TABLE [dbo].[DIM_ANTIVIRUS_PRODUCT]
GO

SELECT * 
INTO DIM_ANTIVIRUS_PRODUCT
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT ANTIVIRUS_PRODUCT_DK
	  ,CAST(SUBSTRING(ANTIVIRUS_PRODUCT,1,8000) AS CHAR(8000)) AS ANTIVIRUS_PRODUCT
	  ,CAST(SUBSTRING(ANTIVIRUS_PRODUCT_VERSION,1,8000) AS CHAR(8000)) AS ANTIVIRUS_PRODUCT_VERSION
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_ANTIVIRUS_PRODUCT')
