USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_BACKUP_PRODUCT]') AND type in (N'U'))
DROP TABLE [dbo].[DIM_BACKUP_PRODUCT]
GO

SELECT * 
INTO DIM_BACKUP_PRODUCT
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT BACKUP_PRODUCT_DK
	  ,BACKUP_PRODUCT_SK
	  ,CAST(SUBSTRING(PLUGIN_DESCRIPTION,1,8000) AS CHAR(8000)) AS PLUGIN_DESCRIPTION
	  ,CAST(SUBSTRING(PLUGIN_NAME,1,8000) AS CHAR(8000)) AS PLUGIN_NAME
	  ,SERVICE_INSTANCE_ID
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_BACKUP_PRODUCT')
