USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_APPLICATION]') AND type in (N'U'))
DROP TABLE [dbo].[DIM_APPLICATION]
GO

SELECT * 
INTO DIM_APPLICATION
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT APPLICATION_DK
	  ,CAST(SUBSTRING(APPLICATION_NAME,1,8000) AS CHAR(8000)) AS APPLICATION_NAME
	  ,CAST(SUBSTRING(APPLICATION_PUBLISHER,1,8000) AS CHAR(8000)) AS APPLICATION_PUBLISHER
	  ,CAST(SUBSTRING(APPLICATION_VERSION,1,8000) AS CHAR(8000)) AS APPLICATION_VERSION
	  ,DSS_CREATED
  FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_APPLICATION')
