USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_TASK_STATE]') AND type in (N'U'))
DROP TABLE [dbo].DIM_TASK_STATE
GO

SELECT * 
INTO DIM_TASK_STATE
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT STATE_DK
	  ,STATE_ID
	  ,CAST(SUBSTRING(STATE,1,8000) AS CHAR(8000)) AS STATE
	  ,CAST(SUBSTRING(STATE_GROUP,1,8000) AS CHAR(8000)) AS STATE_GROUP
	  ,DSS_CREATED
	  ,DSS_UPDATED
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_TASK_STATE')
