USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_TENANT]') AND type in (N'U'))
DROP TABLE [dbo].DIM_TENANT
GO

SELECT * 
INTO DIM_TENANT
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT TENANT_DK
	  ,CAST(SUBSTRING(SYSTEM_GUID,1,8000) AS CHAR(8000)) AS SYSTEM_GUID
	  ,CAST(SUBSTRING(BIZ_APPS_CUST_ID,1,8000) AS CHAR(8000)) AS BIZ_APPS_CUST_ID
	  ,CAST(SUBSTRING(SO_NAME,1,8000) AS CHAR(8000)) AS SO_NAME
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_TENANT')
