USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_REMOTE_EXECUTION_ITEM]') AND type in (N'U'))
DROP TABLE [dbo].DIM_REMOTE_EXECUTION_ITEM
GO

SELECT * 
INTO DIM_REMOTE_EXECUTION_ITEM
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT TENANT_DK
	  ,REMOTE_EXECUTION_ITEM_SK
	  ,REMOTE_EXECUTION_ITEM_DK
	  ,REMOTE_EXECUTION_ITEM_ID
	  ,CAST(SUBSTRING(EARLIEST_ITEM_NAME,1,8000) AS CHAR(8000)) AS EARLIEST_ITEM_NAME
	  ,CAST(SUBSTRING(LATEST_ITEM_NAME,1,8000) AS CHAR(8000)) AS LATEST_ITEM_NAME
	  ,EARLIEST_LAST_UPDATED
	  ,LATEST_LAST_UPDATED
	  ,DSS_CREATED
	  ,DSS_UPDATED
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_REMOTE_EXECUTION_ITEM')
