USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIM_RLS]') AND type in (N'U'))
DROP TABLE [dbo].DIM_RLS
GO

SELECT * 
INTO DIM_RLS
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT TENANT_DK
	  ,USER_DK
	  ,CUSTOMER_DK
	  ,CAST(SUBSTRING(CUSTOMER_TYPE,1,8000) AS CHAR(8000)) AS CUSTOMER_TYPE
	  ,CAST(SUBSTRING(EMAIL,1,8000) AS CHAR(8000)) AS EMAIL
	  ,CAST(SUBSTRING(FIRST_NAME,1,8000) AS CHAR(8000)) AS FIRST_NAME
	  ,CAST(SUBSTRING(LAST_NAME,1,8000) AS CHAR(8000)) AS LAST_NAME
	  ,CAST(SUBSTRING(ROLE_TYPE,1,8000) AS CHAR(8000)) AS ROLE_TYPE
	  ,PARENT_USER_ID
	  ,CAST(SUBSTRING(PARENT_USER_EMAIL,1,8000) AS CHAR(8000)) AS PARENT_USER_EMAIL
	  ,ENABLED
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.DIM_RLS')
