USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FACT_APPLICATION_COUNT]') AND type in (N'U'))
DROP TABLE [dbo].FACT_APPLICATION_COUNT
GO

SELECT * 
INTO FACT_APPLICATION_COUNT
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT TENANT_DK
	  ,DEVICE_SK
	  ,DEVICE_DK
	  ,SITE_SK
	  ,SITE_DK
	  ,CUSTOMER_SK
	  ,CUSTOMER_DK
	  ,DATE_DK
	  ,SNAPSHOT_DATE
	  ,NUM_APPLICATIONS
	  ,NUM_INSTALLATIONS
	  ,NUM_DELETED
	  ,DSS_CREATED
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.FACT_APPLICATION_COUNT')
