USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FACT_BACKUP_SESSION]') AND type in (N'U'))
DROP TABLE [dbo].FACT_BACKUP_SESSION
GO

SELECT * 
INTO FACT_BACKUP_SESSION
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT TENANT_DK
	  ,BACKUP_SESSION_DK
	  ,DEVICE_SK
	  ,DEVICE_DK
	  ,SITE_SK
	  ,SITE_DK
	  ,CUSTOMER_SK
	  ,CUSTOMER_DK
	  ,BACKUP_PRODUCT_SK
	  ,BACKUP_STATUS_SK
	  ,TASK_DK
	  ,DATE_START_SK
	  ,DATE_END_SK
	  ,TIME_START_SK
	  ,TIME_END_SK
	  ,JOB_START_TIMESTAMP
	  ,JOB_START_DATE
	  ,CAST(SUBSTRING(JOB_START_TIME,1,8000) AS CHAR(8000)) AS JOB_START_TIME
	  ,JOB_END_TIMESTAMP
	  ,JOB_END_DATE
	  ,CAST(SUBSTRING(JOB_END_TIME,1,8000) AS CHAR(8000)) AS JOB_END_TIME
	  ,JOB_DURATION_SECONDS
	  ,TOTAL_BYTES_PROCESSED
	  ,TOTAL_PREVIOUS_BYTES_PROCESSED
	  ,TOTAL_GIGABYTES_PROCESSED
	  ,TOTAL_BYTE_CHANGE
	  ,BYTE_RATE
	  ,NUM_ATTEMPTED_BACKUP
	  ,NUM_BACKUP_SUCCESS
	  ,NUM_BACKUP_WARNING
	  ,NUM_BACKUP_FAILED
	  ,DSS_CREATED
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.FACT_BACKUP_SESSION')
