USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FACT_APPLICATION_STATUS]') AND type in (N'U'))
DROP TABLE [dbo].FACT_APPLICATION_STATUS
GO

SELECT * 
INTO FACT_APPLICATION_STATUS
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT TENANT_DK
	  ,DEVICE_SK
	  ,DEVICE_DK
	  ,SITE_SK
	  ,SITE_DK
	  ,CUSTOMER_SK
	  ,CUSTOMER_DK
	  ,DATE_DK
	  ,TIME_SK
	  ,APPLICATION_DK
	  ,DEVICE_APPLICATION_DK
	  ,INSTALLATION_DATE
	  ,VALID_FROM
	  ,VALID_TO
	  ,DSS_IS_DELETE
	  ,DSS_CREATED
	  ,DSS_UPDATED
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.FACT_APPLICATION_STATUS')
