USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FACT_NETWORK_BANDWIDTH_DAY]') AND type in (N'U'))
DROP TABLE [dbo].FACT_NETWORK_BANDWIDTH_DAY
GO

SELECT * 
INTO FACT_NETWORK_BANDWIDTH_DAY
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT *
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.FACT_NETWORK_BANDWIDTH_DAY')
