USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FACT_NETWORK_ERRORS]') AND type in (N'U'))
DROP TABLE [dbo].FACT_NETWORK_ERRORS
GO

SELECT * 
INTO FACT_NETWORK_ERRORS
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT TENANT_DK
	  ,NW_RESPONSETIME_DK
	  ,CUSTOMER_DK
	  ,CUSTOMER_SK
	  ,SITE_DK
	  ,SITE_SK
	  ,DEVICE_DK
	  ,DEVICE_SK
	  ,SERVICE_INSTANCE_DK
	  ,SERVICE_INSTANCE_ID
	  ,EVENT_NW_TIMESTAMP
	  ,SCAN_HOUR_DATETIME
	  ,EVENT_DATE_DK
	  ,EVENT_TIME_SK
	  ,NW_RESPONSETIME_STATE_ID
	  ,CAST(SUBSTRING(ERROR_MESSAGE,1,8000) AS CHAR(8000)) AS ERROR_MESSAGE
	  ,NUM_ERROR
	  ,NW_PACKET_LOSS_PCT
	  ,TIME_TO_LIVE_HOPS
	  ,DSS_CREATED
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.FACT_NETWORK_ERRORS')
