USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FACT_ANTIVIRUS_STATUS_LATEST]') AND type in (N'U'))
DROP TABLE [dbo].FACT_ANTIVIRUS_STATUS_LATEST
GO

SELECT * 
INTO FACT_ANTIVIRUS_STATUS_LATEST
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT TENANT_DK
	  ,ANTIVIRUS_SECURITY_DK
	  ,CUSTOMER_DK
	  ,CUSTOMER_SK
	  ,SITE_DK
	  ,SITE_SK
	  ,DEVICE_DK
	  ,DEVICE_SK
	  ,ANTIVIRUS_PRODUCT_DK
	  ,ANTIVIRUS_PRODUCT_STATUS_DK
	  ,ANTIVIRUS_STATUS_TIMESTAMP
	  ,STATUS_DATE_DK
	  ,NUM_DAYS_FROM_LAST_SCAN
	  ,DEFINITIONS_AGE
	  ,STATUS_COUNT
	  ,NUM_SCANNING_ENABLED
	  ,NUM_SCANNING_DISABLED
	  ,NUM_DEFINITIONS_UP_TO_DATE
	  ,NUM_DEFINITIONS_OUT_OF_DATE
	  ,DSS_CREATED
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.FACT_ANTIVIRUS_STATUS_LATEST
	WHERE DSS_CREATED > ''2024-04-01 00:00:00.0000000''')
