USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FACT_DEVICE_INCIDENT]') AND type in (N'U'))
DROP TABLE [dbo].FACT_DEVICE_INCIDENT
GO

SELECT * 
INTO FACT_DEVICE_INCIDENT
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT TENANT_DK
	  ,INCIDENT_DK
	  ,CUSTOMER_DK
	  ,CUSTOMER_SK
	  ,SITE_DK
	  ,SITE_SK
	  ,DEVICE_DK
	  ,DEVICE_SK
	  ,SERVICE_INSTANCE_DK
	  ,TIME_OPENED_TIMESTAMP
	  ,TIME_CLOSED_EARLIEST_TIMESTAMP
	  ,TIME_CLOSED_LATEST_TIMESTAMP
	  ,INCIDENT_DATE_OPENED_DK
	  ,INCIDENT_TIME_OPENED_SK
	  ,INCIDENT_DATE_CLOSED_EARLIEST_DK
	  ,INCIDENT_TIME_CLOSED_EARLIEST_SK
	  ,INCIDENT_DATE_CLOSED_LATEST_DK
	  ,INCIDENT_TIME_CLOSED_LATEST_SK
	  ,INCIDENT_ID
	  ,SERVICE_INSTANCE_ID
	  ,NUM_INCIDENTS
	  ,DSS_CREATED
	  ,DSS_UPDATED
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.FACT_DEVICE_INCIDENT')
