USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FACT_PHYSICAL_STORAGE_LATEST]') AND type in (N'U'))
DROP TABLE [dbo].FACT_PHYSICAL_STORAGE_LATEST
GO

SELECT * 
INTO FACT_PHYSICAL_STORAGE_LATEST
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT *
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.FACT_PHYSICAL_STORAGE_LATEST')
