--FACT_OS_REBOOT_LATEST
USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FACT_OS_REBOOT_LATEST]') AND type in (N'U'))
DROP TABLE [dbo].FACT_OS_REBOOT_LATEST
GO

SELECT * 
INTO FACT_OS_REBOOT_LATEST
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT *
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.FACT_OS_REBOOT_LATEST')
