USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FACT_DEVICE_LAST_LOGON]') AND type in (N'U'))
DROP TABLE [dbo].FACT_DEVICE_LAST_LOGON
GO

SELECT * 
INTO FACT_DEVICE_LAST_LOGON
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT TENANT_DK
	  ,DEVICE_LOGON_DK
	  ,CUSTOMER_DK
	  ,CUSTOMER_SK
	  ,SITE_DK
	  ,SITE_SK
	  ,DEVICE_DK
	  ,DEVICE_SK
	  ,DOMAIN_USER_DK
	  ,LOGON_TIMESTAMP
	  ,LOGON_DATE_DK
	  ,LOGON_TIME_SK
	  ,NUM_DEVICE_LOGON
	  ,STILL_LOGGED_IN
	  ,DSS_CREATED
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.FACT_DEVICE_LAST_LOGON')
