USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FACT_ANTIVIRUS_THREAT]') AND type in (N'U'))
DROP TABLE [dbo].FACT_ANTIVIRUS_THREAT
GO

SELECT * 
INTO FACT_ANTIVIRUS_THREAT
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT TENANT_DK
	  ,ANTIVIRUS_SECURITY_THREAT_DK
	  ,CUSTOMER_DK
	  ,CUSTOMER_SK
	  ,SITE_DK
	  ,SITE_SK
	  ,DEVICE_DK
	  ,DEVICE_SK
	  ,ANTIVIRUS_THREAT_DK
	  ,ANTIVIRUS_ACTION_DK
	  ,ANTIVIRUS_OUTCOME_DK
	  ,THREAT_TIMESTAMP
	  ,THREAT_DATE_DK
	  ,THREAT_TIME_SK
	  ,NUM_THREATS
	  ,NUM_OUTCOME
	  ,NUM_OUTCOME_PRESENT
	  ,NUM_OUTCOME_DELETED
	  ,NUM_OUTCOME_BLOCKED
	  ,NUM_OUTCOME_QUARANTINED
	  ,NUM_OUTCOME_CLEANED
	  ,NUM_OUTCOME_RESTORED
	  ,NUM_OUTCOME_IGNORED
	  ,NUM_OUTCOME_MANUALLYRESOLVED
	  ,NUM_OUTCOME_FALSEPOSITIVE
	  ,NUM_OUTCOME_TICKED
	  ,NUM_OUTCOME_UNKNOWN
	  ,DSS_CREATED
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.FACT_ANTIVIRUS_THREAT')
