USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FACT_VIDEO_CONTROLLER_LATEST]') AND type in (N'U'))
DROP TABLE [dbo].FACT_VIDEO_CONTROLLER_LATEST
GO

SELECT * 
INTO FACT_VIDEO_CONTROLLER_LATEST
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT *
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.FACT_VIDEO_CONTROLLER_LATEST')
