USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FACT_BACKUP_STATUS]') AND type in (N'U'))
DROP TABLE [dbo].FACT_BACKUP_STATUS
GO

SELECT * 
INTO FACT_BACKUP_STATUS
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT TENANT_DK
	  ,DEVICE_DK
	  ,BACKUP_PRODUCT_SK
	  ,STATUS_1
	  ,STATUS_2
	  ,STATUS_3
	  ,STATUS_4
	  ,STATUS_5
	  ,CAST(SUBSTRING(LAST_28_SESSIONS,1,8000) AS CHAR(8000)) AS LAST_28_SESSIONS
	  ,LAST_SUCCESS_START_TIMESTAMP
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.FACT_BACKUP_STATUS')
