USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FACT_FIREWALL_INCIDENT]') AND type in (N'U'))
DROP TABLE [dbo].FACT_FIREWALL_INCIDENT
GO

SELECT * 
INTO FACT_FIREWALL_INCIDENT
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT *
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.FACT_FIREWALL_INCIDENT')
