USE SNOWFLAKE
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FACT_ASSET_COUNT_DAY]') AND type in (N'U'))
DROP TABLE [dbo].FACT_ASSET_COUNT_DAY
GO

SELECT * 
INTO FACT_ASSET_COUNT_DAY
FROM OPENQUERY([NABLESNOWFLAKE], 'SELECT TENANT_DK
	  ,CUSTOMER_SK
	  ,CUSTOMER_DK
	  ,SITE_SK
	  ,SITE_DK
	  ,DEVICE_SK
	  ,DEVICE_DK
	  ,SNAPSHOT_DATE_DK
	  ,SNAPSHOT_DATE
	  ,NUM_MANAGED
	  ,NUM_DEVICE
	  ,CAST(SUBSTRING(NUM_DELETED,1,8000) AS CHAR(8000)) AS NUM_DELETED
	FROM SHARED_ANALYTICS_DATA.SHARED_DATA.FACT_ASSET_COUNT_DAY')
